### ISSUE TITLE
picture is so big,a ha ..

### ISSUE THREAD

**Issue by fanrunqi** [dreamlivemeng/ZxingScan#2]
<img src="pic_url" width = "232" height = "386"  />

**Comment by dreamlivemeng** [comment]
图片链接失效了。是扫描图片太大了，导致失败吗？

**Comment by fanrunqi** [comment]
转存一下 图片大小做的小一点。我是把图片放在 io那个项目里的。不会失效

**Comment by dreamlivemeng** [comment]
其实对于大图的话，建议通过把图片链接生成二维码，然后再扫描获取连接，最后在本地加载图片链接的方式。
